package cn.com.reachmedia.rmhandle.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMM_DOOR_PIC_BEAN.
 */
public class CommDoorPicBean {

    private Long id;
    private String userId;
    private String communityId;
    private String communityFile1;
    private String communityFileId1;
    private String communitySpace1;
    private String communitySpaceId1;
    private String communityFile2;
    private String communityFileId2;
    private String communitySpace2;
    private String communitySpaceId2;
    private java.util.Date workTime;
    private String nativeState;

    public CommDoorPicBean() {
    }

    public CommDoorPicBean(Long id) {
        this.id = id;
    }

    public CommDoorPicBean(Long id, String userId, String communityId, String communityFile1, String communityFileId1, String communitySpace1, String communitySpaceId1, String communityFile2, String communityFileId2, String communitySpace2, String communitySpaceId2, java.util.Date workTime, String nativeState) {
        this.id = id;
        this.userId = userId;
        this.communityId = communityId;
        this.communityFile1 = communityFile1;
        this.communityFileId1 = communityFileId1;
        this.communitySpace1 = communitySpace1;
        this.communitySpaceId1 = communitySpaceId1;
        this.communityFile2 = communityFile2;
        this.communityFileId2 = communityFileId2;
        this.communitySpace2 = communitySpace2;
        this.communitySpaceId2 = communitySpaceId2;
        this.workTime = workTime;
        this.nativeState = nativeState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getCommunityId() {
        return communityId;
    }

    public void setCommunityId(String communityId) {
        this.communityId = communityId;
    }

    public String getCommunityFile1() {
        return communityFile1;
    }

    public void setCommunityFile1(String communityFile1) {
        this.communityFile1 = communityFile1;
    }

    public String getCommunityFileId1() {
        return communityFileId1;
    }

    public void setCommunityFileId1(String communityFileId1) {
        this.communityFileId1 = communityFileId1;
    }

    public String getCommunitySpace1() {
        return communitySpace1;
    }

    public void setCommunitySpace1(String communitySpace1) {
        this.communitySpace1 = communitySpace1;
    }

    public String getCommunitySpaceId1() {
        return communitySpaceId1;
    }

    public void setCommunitySpaceId1(String communitySpaceId1) {
        this.communitySpaceId1 = communitySpaceId1;
    }

    public String getCommunityFile2() {
        return communityFile2;
    }

    public void setCommunityFile2(String communityFile2) {
        this.communityFile2 = communityFile2;
    }

    public String getCommunityFileId2() {
        return communityFileId2;
    }

    public void setCommunityFileId2(String communityFileId2) {
        this.communityFileId2 = communityFileId2;
    }

    public String getCommunitySpace2() {
        return communitySpace2;
    }

    public void setCommunitySpace2(String communitySpace2) {
        this.communitySpace2 = communitySpace2;
    }

    public String getCommunitySpaceId2() {
        return communitySpaceId2;
    }

    public void setCommunitySpaceId2(String communitySpaceId2) {
        this.communitySpaceId2 = communitySpaceId2;
    }

    public java.util.Date getWorkTime() {
        return workTime;
    }

    public void setWorkTime(java.util.Date workTime) {
        this.workTime = workTime;
    }

    public String getNativeState() {
        return nativeState;
    }

    public void setNativeState(String nativeState) {
        this.nativeState = nativeState;
    }

}
