package cn.com.reachmedia.rmhandle.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMP_IMAGE_BEAN.
 */
public class CompImageBean {

    private Long id;
    private String userid;
    private String workid;
    private String pointid;
    private String source_path;
    private String target_path;
    private Boolean water_mask;
    private java.util.Date create_time;
    private java.util.Date compress_time;
    private Integer state;

    public CompImageBean() {
    }

    public CompImageBean(Long id) {
        this.id = id;
    }

    public CompImageBean(Long id, String userid, String workid, String pointid, String source_path, String target_path, Boolean water_mask, java.util.Date create_time, java.util.Date compress_time, Integer state) {
        this.id = id;
        this.userid = userid;
        this.workid = workid;
        this.pointid = pointid;
        this.source_path = source_path;
        this.target_path = target_path;
        this.water_mask = water_mask;
        this.create_time = create_time;
        this.compress_time = compress_time;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getWorkid() {
        return workid;
    }

    public void setWorkid(String workid) {
        this.workid = workid;
    }

    public String getPointid() {
        return pointid;
    }

    public void setPointid(String pointid) {
        this.pointid = pointid;
    }

    public String getSource_path() {
        return source_path;
    }

    public void setSource_path(String source_path) {
        this.source_path = source_path;
    }

    public String getTarget_path() {
        return target_path;
    }

    public void setTarget_path(String target_path) {
        this.target_path = target_path;
    }

    public Boolean getWater_mask() {
        return water_mask;
    }

    public void setWater_mask(Boolean water_mask) {
        this.water_mask = water_mask;
    }

    public java.util.Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

    public java.util.Date getCompress_time() {
        return compress_time;
    }

    public void setCompress_time(java.util.Date compress_time) {
        this.compress_time = compress_time;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
