package cn.com.reachmedia.rmhandle.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE_CACHE_BEAN.
 */
public class ImageCacheBean {

    private Long id;
    private String url;
    private String path;
    private java.util.Date start_time;
    private java.util.Date create_time;
    private Long index;
    private String community_id;

    public ImageCacheBean() {
    }

    public ImageCacheBean(Long id) {
        this.id = id;
    }

    public ImageCacheBean(Long id, String url, String path, java.util.Date start_time, java.util.Date create_time, Long index, String community_id) {
        this.id = id;
        this.url = url;
        this.path = path;
        this.start_time = start_time;
        this.create_time = create_time;
        this.index = index;
        this.community_id = community_id;
    }

    public ImageCacheBean(String url, String path, java.util.Date start_time, java.util.Date create_time, Long index, String community_id) {
        this.url = url;
        this.path = path;
        this.start_time = start_time;
        this.create_time = create_time;
        this.index = index;
        this.community_id = community_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public java.util.Date getStart_time() {
        return start_time;
    }

    public void setStart_time(java.util.Date start_time) {
        this.start_time = start_time;
    }

    public java.util.Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

    public Long getIndex() {
        return index;
    }

    public void setIndex(Long index) {
        this.index = index;
    }

    public String getCommunity_id() {
        return community_id;
    }

    public void setCommunity_id(String community_id) {
        this.community_id = community_id;
    }

}
