package cn.com.reachmedia.rmhandle.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POINT_BEAN.
 */
public class PointBean {

    private Long id;
    private String userId;
    private String workId;
    private String cid;
    private String cname;
    private String doorId;
    private String door;
    private Integer workUp;
    private Integer workUpPhone;
    private Integer workDown;
    private Integer workDownPhone;
    private Integer workCheck;
    private String pointId;
    private Integer ground;
    private String cDoorPic;
    private String errorDesc;
    private Integer isPhoto;
    private Integer state;
    private Integer stateType;
    private String updateTime;
    private String pictime;
    private String worktime;
    private java.util.Date starttime;
    private java.util.Date endtime;
    private String communityid;
    private String fileId;
    private String fileUrlB;
    private String fileUrlS;

    public PointBean() {
    }

    public PointBean(Long id) {
        this.id = id;
    }

    public PointBean(Long id, String userId, String workId, String cid, String cname, String doorId, String door, Integer workUp, Integer workUpPhone, Integer workDown, Integer workDownPhone, Integer workCheck, String pointId, Integer ground, String cDoorPic, String errorDesc, Integer isPhoto, Integer state, Integer stateType, String updateTime, String pictime, String worktime, java.util.Date starttime, java.util.Date endtime, String communityid, String fileId, String fileUrlB, String fileUrlS) {
        this.id = id;
        this.userId = userId;
        this.workId = workId;
        this.cid = cid;
        this.cname = cname;
        this.doorId = doorId;
        this.door = door;
        this.workUp = workUp;
        this.workUpPhone = workUpPhone;
        this.workDown = workDown;
        this.workDownPhone = workDownPhone;
        this.workCheck = workCheck;
        this.pointId = pointId;
        this.ground = ground;
        this.cDoorPic = cDoorPic;
        this.errorDesc = errorDesc;
        this.isPhoto = isPhoto;
        this.state = state;
        this.stateType = stateType;
        this.updateTime = updateTime;
        this.pictime = pictime;
        this.worktime = worktime;
        this.starttime = starttime;
        this.endtime = endtime;
        this.communityid = communityid;
        this.fileId = fileId;
        this.fileUrlB = fileUrlB;
        this.fileUrlS = fileUrlS;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getWorkId() {
        return workId;
    }

    public void setWorkId(String workId) {
        this.workId = workId;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getCname() {
        return cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getDoorId() {
        return doorId;
    }

    public void setDoorId(String doorId) {
        this.doorId = doorId;
    }

    public String getDoor() {
        return door;
    }

    public void setDoor(String door) {
        this.door = door;
    }

    public Integer getWorkUp() {
        return workUp;
    }

    public void setWorkUp(Integer workUp) {
        this.workUp = workUp;
    }

    public Integer getWorkUpPhone() {
        return workUpPhone;
    }

    public void setWorkUpPhone(Integer workUpPhone) {
        this.workUpPhone = workUpPhone;
    }

    public Integer getWorkDown() {
        return workDown;
    }

    public void setWorkDown(Integer workDown) {
        this.workDown = workDown;
    }

    public Integer getWorkDownPhone() {
        return workDownPhone;
    }

    public void setWorkDownPhone(Integer workDownPhone) {
        this.workDownPhone = workDownPhone;
    }

    public Integer getWorkCheck() {
        return workCheck;
    }

    public void setWorkCheck(Integer workCheck) {
        this.workCheck = workCheck;
    }

    public String getPointId() {
        return pointId;
    }

    public void setPointId(String pointId) {
        this.pointId = pointId;
    }

    public Integer getGround() {
        return ground;
    }

    public void setGround(Integer ground) {
        this.ground = ground;
    }

    public String getCDoorPic() {
        return cDoorPic;
    }

    public void setCDoorPic(String cDoorPic) {
        this.cDoorPic = cDoorPic;
    }

    public String getErrorDesc() {
        return errorDesc;
    }

    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc;
    }

    public Integer getIsPhoto() {
        return isPhoto;
    }

    public void setIsPhoto(Integer isPhoto) {
        this.isPhoto = isPhoto;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getStateType() {
        return stateType;
    }

    public void setStateType(Integer stateType) {
        this.stateType = stateType;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getPictime() {
        return pictime;
    }

    public void setPictime(String pictime) {
        this.pictime = pictime;
    }

    public String getWorktime() {
        return worktime;
    }

    public void setWorktime(String worktime) {
        this.worktime = worktime;
    }

    public java.util.Date getStarttime() {
        return starttime;
    }

    public void setStarttime(java.util.Date starttime) {
        this.starttime = starttime;
    }

    public java.util.Date getEndtime() {
        return endtime;
    }

    public void setEndtime(java.util.Date endtime) {
        this.endtime = endtime;
    }

    public String getCommunityid() {
        return communityid;
    }

    public void setCommunityid(String communityid) {
        this.communityid = communityid;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getFileUrlB() {
        return fileUrlB;
    }

    public void setFileUrlB(String fileUrlB) {
        this.fileUrlB = fileUrlB;
    }

    public String getFileUrlS() {
        return fileUrlS;
    }

    public void setFileUrlS(String fileUrlS) {
        this.fileUrlS = fileUrlS;
    }

}
