package cn.com.reachmedia.rmhandle.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.com.reachmedia.rmhandle.bean.PointBean;
import cn.com.reachmedia.rmhandle.bean.PointWorkBean;

import cn.com.reachmedia.rmhandle.dao.PointBeanDao;
import cn.com.reachmedia.rmhandle.dao.PointWorkBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pointBeanDaoConfig;
    private final DaoConfig pointWorkBeanDaoConfig;

    private final PointBeanDao pointBeanDao;
    private final PointWorkBeanDao pointWorkBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pointBeanDaoConfig = daoConfigMap.get(PointBeanDao.class).clone();
        pointBeanDaoConfig.initIdentityScope(type);

        pointWorkBeanDaoConfig = daoConfigMap.get(PointWorkBeanDao.class).clone();
        pointWorkBeanDaoConfig.initIdentityScope(type);

        pointBeanDao = new PointBeanDao(pointBeanDaoConfig, this);
        pointWorkBeanDao = new PointWorkBeanDao(pointWorkBeanDaoConfig, this);

        registerDao(PointBean.class, pointBeanDao);
        registerDao(PointWorkBean.class, pointWorkBeanDao);
    }
    
    public void clear() {
        pointBeanDaoConfig.getIdentityScope().clear();
        pointWorkBeanDaoConfig.getIdentityScope().clear();
    }

    public PointBeanDao getPointBeanDao() {
        return pointBeanDao;
    }

    public PointWorkBeanDao getPointWorkBeanDao() {
        return pointWorkBeanDao;
    }

}
